<?php

/**
 * Sequence of a standard request:
 *
 * -- START OF BOOTSTRAP
 * hook_boot()
 * hook_init()
 * -- END OF BOOTSTRAP
 * menu_execute_active_handler()
 *   -- execute menu callback    <-- main page content
 *   drupal_deliver_page()
 *     drupal_deliver_html_page()
 *       drupal_render_page()
 *         hook_page_build()     <-- blocks ...
 *         hook_page_alter()
 *         drupal_render()
 *     drupal_page_footer()
 *       hook_exit()
 *       -- write caches
 *       -- run cron
 */

/**
 * Fake query to show a message in devel's query log.
 */
function sb_stagemarker_message($msg) {
  $time = timer_read('page');
  $mem_usage = round(memory_get_usage() / 1024 / 1024, 2);
  $mem_peak = round(memory_get_peak_usage(TRUE) / 1024 / 1024, 2);
  $msg .= " | Execution time: $time ms | Memory usage: $mem_usage MB | Memory peak: $mem_peak MB";
  watchdog('STAGEMARKER', $msg);

  if (variable_get('devel_query_display', FALSE) && variable_get('devel_query_sort') == 0) {
    db_query("SELECT 'STAGEMARKER: $msg'");
  }
}

/**
 *  * Discern if $hook has to be observed.
 *   */
function sb_stagemarker_observe($hook) {
  static $observed = NULL;
  if (is_null($observed)) {
    $observed = variable_get('sb_stagemarker_observed_hooks', array());
    $observed = array_combine($observed, $observed);
  }
  return isset($observed[$hook]);
}

/**
 * Implements hook_menu_site_status_alter().
 *
 * Last hook available before calling the page callback function.
 *
 * @see menu_execute_active_handler().
 */
function sb_stagemarker_menu_site_status_alter() {
  timer_start('stagemarker_page_callback');
  sb_stagemarker_message("BEFORE MENU CALLBACK EXECUTION");
}

/**
 * Implements hook_page_delivery_callback_alter().
 *
 * First hook available after calling the page callback function.
 *
 * @see menu_execute_active_handler().
 * @see drupal_deliver_page().
 */
function sb_stagemarker_page_delivery_callback_alter() {
  $time = timer_read('stagemarker_page_callback');
  sb_stagemarker_message("AFTER  MENU CALLBACK EXECUTION [${time}ms]");
}

