<?php

/**
 * Implements hook_module_implements_alter().
 *
 * Place all our hook implementations at the end.
 */
function sb_stagemarker_after_module_implements_alter(&$implementations, $hook) {
  $self = 'sb_stagemarker_after';
  if (isset($implementations[$self])) {
    $group = $implementations[$self];
    unset($implementations[$self]);
    $implementations[$self] = $group;
  }
}

/**
 * Writes a mark after invoking an observed hook.
 *
 * @see sb_stagemarker_observe()
 */
function sb_stagemarker_after_invoke($hook, $module) {
  if (sb_stagemarker_observe($hook) && !(strpos($module, 'sb_stagemarker') === 0)) {
    $function = $module .'_'. $hook;
    $time = timer_read("stagemarker_$function");
    sb_stagemarker_message("AFTER  INVOKE $hook $module [${time}ms]");
  }
}

/**
 * Implements hook_boot().
 */
function sb_stagemarker_after_boot() {
  // It's too early. Modules hasn't been included yet.
  require_once dirname(__FILE__) . '/sb_stagemarker.module';

  #TODO# Check module is not being enabled? See https://www.drupal.org/node/2324587

  #$time = timer_read('stagemarker_boot');
  #sb_stagemarker_message("AFTER  HOOK BOOT [${time}ms]");
}

/**
 * Implements hook_init().
 */
function sb_stagemarker_after_init() {
  $time = timer_read('stagemarker_init');
  sb_stagemarker_message("AFTER  HOOK INIT [${time}ms]");
}

/**
 * Implements hook_cron().
 */
function sb_stagemarker_after_cron() {
  $time = timer_read('stagemarker_cron');
  sb_stagemarker_message("AFTER  HOOK CRON [${time}ms]");
}

/**
 * Implements hook_page_build().
 *
 * @see drupal_render_page().
 */
function sb_stagemarker_after_page_build() {
  $time = timer_read('stagemarker_page_build');
  sb_stagemarker_message("AFTER  HOOK PAGE BUILD [${time}ms]");
}

/**
 * Implements hook_page_alter().
 *
 * @see drupal_render_page().
 */
function sb_stagemarker_after_page_alter() {
  $time = timer_read('stagemarker_page_alter');
  sb_stagemarker_message("AFTER  PAGE ALTER [${time}ms]");
}

/**
 * Implements hook_exit().
 */
function sb_stagemarker_after_exit() {
  $time = timer_read('stagemarker_exit');
  sb_stagemarker_message("AFTER  HOOK EXIT [${time}ms]");
}

